{% set name = "link-traits" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/link_traits-{{ version }}.tar.gz
  sha256: 4e1f104ce3bcb9a1c16f838d19ff45ec7be9704df6565690de19b0a05d5820a9

build:
  number: 3
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - traits

test:
  imports:
    - link_traits
  commands:
    - pip check
    - pytest --pyargs link_traits
  requires:
    - pytest
    - traitlets

about:
  home: https://github.com/hyperspy/link_traits
  license: BSD-3-Clause
  summary: A fork to traitlets' link and dlink to link traits in addition to traitlets.
  license_file: COPYING.md
extra:
  recipe-maintainers:
    - to266
    - francisco-dlp
    - ericpre
