travis:
  secure:
    BINSTAR_TOKEN: dUJN/ZP+lBU+IHHTXcPVj2KQ/d4TRHZ/ob1m4Z7yt52uafQU0zF0Xh2Wudxvd6lPyM0n4pdaiklnH2R8xLR2amdAIUWe8p8IhNxSWGxxyeRZNjGNE3HM7jRKRf/2xdnbzcdU8ekYka2G3tmAKCv9kUN135LBJ5PccfvhtoFPS0TXSHDiqKABV0ZD6vD81jvnfurgdqV3s5BI/O9zI8dlaljxyz7GnvzWwqkfUVYBSW+yyMkiAnKoLFUqJQWjcmOF13WiEY6kJFm1kALOI/9op1r4BtiKH+PmImyW84kGRbyzvPBBxcTkGi0x1Fj6ZMvTeGxOAb/b0muQ+T6fS4at3Axc7Zp/wU2ouQDE9G1deefVrQjOnw9DZCkpgmiWUVtH2l9K/RXCtjREfJLqWMspkZ5VpqLxix49JPeYx5IqSeVUs6bgwQG3+JJPmc57qQkl21IQ4GjbUr1J3aHKV3CcGypwrxsD8oF0SJGGCCKOU6Q5NL5XY/NnEgtVqXyAXvkulxmkGv0b5uAvI4bcYqbAdPqIrk4AF0FjSwmWwufpnGUssqSp1s9U/kh7ZatwQszgeQFi+lYs/i26DzKxNj5mCQFRPdoPPa2RRQhP2xNOY2lMoqo3N59/yHafWQgRG0ckMkMqAnERZQqHKXpRmLMWqPoV0C7k6S9wpN+QGQDIPx4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
