appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Hspl5xB8WKLXjiHrXU5LYhl4eJW78ol2/+NviINtJ0tOJ+CrGZVV8+Bx6Eu1ZKy8813M4+BJnAJQxoPSIuBu7c4pdYEsRkU0UkBiLXPzP4fY8XesLfLO7DVagDzu0vTD/UK4X3Qsa6CDtGApPNsS7/LVLaiLpF8vWP7WdxpdbsW7JrSVb0Y/qitSIRATooucaQJZzJffgf5zKu6NycIjNw7AwWWqtEKNKUAhR0cZSmaALG17S3lrfz/wAL6H8hnY4X7nK+7Bn/lWeHvig/M94oc1wqTl5gfyDcnUtQHPwn1YC34SuXDhIVDQBj5xAOdyeUGUfc4R/YLHxvtVOJo+hkvZSqUHBMGht+PSvUB1Zw4gTvFDqYoPTr1e0CrzIh0INUDPlASLxjmHhFPWXyJnqq2eSXTqwszqzK/6DB2R6jOviiEPyCM9kq8+I+OI5uMk7CyPr9D0fBcdiQYdAwW4/o+/9TyZVHMqr7SygmJmcI8CKbXgjUtg5+F5G8LJFExtlylPjwTLoCFdMF3qyz2NwS9nJ9lfK9q/o7X1RacxXb8qYJO0kFDWmfmzFcO+tJbooA9aiCmDoKDTaA5mNVi0mNmlob5/jjRaz/v/VliB+cQs7gCwsgb9mpI7E4eh2qa4Ef1woM7aCYBn9A6H/Lie7tTKVIttYbodSvJ7UkRPJR0=}
